"""empty message

Revision ID: 07c21c96e642
Revises: 5c0aa0036985
Create Date: 2021-03-23 03:15:47.439133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c21c96e642'
down_revision = '5c0aa0036985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_property', sa.Column('imageurl', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('my_property', 'imageurl')
    # ### end Alembic commands ###
