"""empty message

Revision ID: 5c0aa0036985
Revises: 5ba6004aa588
Create Date: 2021-03-23 03:14:29.306828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c0aa0036985'
down_revision = '5ba6004aa588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('my_property', 'imageurl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_property', sa.Column('imageurl', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
