"""empty message

Revision ID: 826c022d5442
Revises: d8acb57e6b5d
Create Date: 2021-03-23 10:36:41.085484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826c022d5442'
down_revision = 'd8acb57e6b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('my_property', 'price')
    op.drop_column('my_property', 'rooms')
    op.drop_column('my_property', 'filename')
    op.drop_column('my_property', 'bathrooms')
    op.drop_column('my_property', 'description')
    op.drop_column('my_property', 'title')
    op.drop_column('my_property', 'ptype')
    op.drop_column('my_property', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_property', sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('my_property', sa.Column('ptype', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('my_property', sa.Column('title', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('my_property', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('my_property', sa.Column('bathrooms', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('my_property', sa.Column('filename', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('my_property', sa.Column('rooms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('my_property', sa.Column('price', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
