"""empty message

Revision ID: d8acb57e6b5d
Revises: 07c21c96e642
Create Date: 2021-03-23 03:26:23.767016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8acb57e6b5d'
down_revision = '07c21c96e642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_property', sa.Column('filename', sa.String(length=120), nullable=True))
    op.drop_column('my_property', 'imageurl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_property', sa.Column('imageurl', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('my_property', 'filename')
    # ### end Alembic commands ###
